---
title: "Before the Workshop"
subtitle: "Actuarial Data Manipulation with R -- CAS Spring Meeting 2024"
author: Denis Dreano
theme: metropolis
date: 5/5/2024
format:
  beamer:
    aspectratio: 169
    fontsize: 8pt
    urlcolor: blue
execute:
  echo: true
---

## Checklist

Here a few steps to prepare for the workshop:

1. Install R and RStudio
2. Install the required packages
3. Download the workshop material
4. Test your setup
5. Refresh your R skills
6. Get familiar with RStudio and the workshop material

## 1) Install R and RStudio

### You will need to bring a laptop with R and RStudio installed

* Case 1: You bring your personal laptop
  - Install R from [CRAN](https://cran.r-project.org/)
  - Install RStudio from [RStudio](https://www.rstudio.com/products/rstudio/download/)

* Case 2: You use a laptop provided by your employer
  - Check with your IT department how to install R and RStudio

## 2) Install the required packages

### Install the `tidyverse` and `ChainLadder` packages

Open the R console in RStudio and run the following command:

```r
install.packages(c("tidyverse", "ChainLadder"))
```

### Test the Installed Packages

Open the R console in RStudio and run the following command:

```r
library(tidyverse)
library(ChainLadder)
```

### Troubleshooting

If you encounter any issue, please reach out to me by email at:
`denis.dreano@protonmail.ch`

## 3) Download the workshop material

1. Download the workshop material using [this link](https://github.com/dreanod/cas2024/releases/download/v1-alpha/cas2024.zip)
2. Unzip the file `cas2024.zip` in a folder of your choice
3. Open the file `cas2024.Rproj` with RStudio. This will open a new RStudio project with the workshop material.

## 4) Test your setup

Open each of the following files in RStudio and run the code by clicking on the
"Source" button (top right corner of the script editor), or with the keyboard
shortcut `Ctrl + Shift + S`:

- `Workshop/part1_solution_indication.R`
- `Workshop/part2_solution_earned_premium.R`
- `Workshop/part3_solution_claim_development.R`

If you you see any error message, please reach out to me by email at:
`denis.dreano@protonmail.ch`

## 5) Refresh your R skills

Make sure you are comfortable with the basic syntax of R:

- assignment (`<-`)
- functions
- control structures (if, else, for, while)
- basic operations (+, -, *, /, ^)
- logical operators (<, >, ==, !=, &, |)
- missing values (`NA`)

If you need a refresher, I included a short R tutorial in the `Slides/` folder
of the workshop material.

If you are not familiar with R, you can follow the free online course
[Introduction to R](https://www.datacamp.com/courses/free-introduction-to-r) on
DataCamp.

## 6) Get familiar with RStudio and the workshop material

If you're not familiar with RStudio, check out:

* this 6-minute video [RStudio for the Total Beginner](https://youtu.be/FIrsOBy5k58?si=OTpgpTeNd3Gux1bF)
* The RStudio cheatsheet in the `Cheatsheets/` folder

Open the workshop material in RStudio
  * `Data/`: Raw data you will need to 
  * `References/`: Original source for the rate indication
  * `Slides/`: This slide and other resources
  * `Videos/`: Introductory videos to the workshop and each module
  * `Workshop/`: The exercises and the solutions
  





